name: Release from Dev

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag version (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed for tags and merging
          ref: Dev         # always start from Dev branch

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Checkout Release branch
        run: |
          if git show-ref --verify --quiet refs/heads/Release; then
            git checkout Release
          else
            git checkout -b Release
          fi

      - name: Merge Dev into Release
        run: |
          git checkout Release
          git merge origin/Dev --no-ff -m "Merge Dev into Release"
          git push origin Release

      - name: Create and push tag
        run: |
          TAG=${{ github.event.inputs.tag }}
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"
